import { getRecords as _getRecords } from "./mux-records-map.js";
export const getRecords = _getRecords;
import { getWritesId as _getWritesId, setWritesId as _setWritesId } from "./mux-writes-id.js";
export const getWritesId = _getWritesId;
export const setWritesId = _setWritesId;
import { getIdentId as _getIdentId, setIdentId as _setIdentId } from "./mux-ident-id.js";
export const getIdentId = _getIdentId;
export const setIdentId = _setIdentId;
import { getEs as _getEs, setEs as _setEs } from "./stream-mux-es.js";
export const getEs = _getEs;
export const setEs = _setEs;
import { nextId as _nextId } from "./mux-next-id.js";
export const nextId = _nextId;
import { isReopenPending as _isReopenPending, setReopenPending as _setReopenPending } from "./mux-reopen-flag.js";
export const isReopenPending = _isReopenPending;
export const setReopenPending = _setReopenPending;
import { isPageReady as _isPageReady, markPageReady as _markPageReady } from "./mux-page-ready.js";
export const isPageReady = _isPageReady;
export const markPageReady = _markPageReady;
