import type { BaseVoxlabComponent } from "../../../../../managers/voxlab/base/base-voxlab-component.js";

export interface FooterPanelSections {
    readonly mesh: BaseVoxlabComponent;
    readonly surface: BaseVoxlabComponent;
    readonly emissive: BaseVoxlabComponent;
    readonly coatSheen: BaseVoxlabComponent;
    readonly wireframe: BaseVoxlabComponent;
    readonly background: BaseVoxlabComponent;
    readonly gridAxes: BaseVoxlabComponent;
    readonly camera: BaseVoxlabComponent;
    readonly motion: BaseVoxlabComponent;
    readonly quality: BaseVoxlabComponent;
    readonly bloom: BaseVoxlabComponent;
    readonly outline: BaseVoxlabComponent;
    readonly stress: BaseVoxlabComponent;
    readonly pixelRatio: BaseVoxlabComponent;
    readonly vignette: BaseVoxlabComponent;
    readonly contrast: BaseVoxlabComponent;
    readonly chromaticAberration: BaseVoxlabComponent;
    readonly colorSpace: BaseVoxlabComponent;
    readonly targetFps: BaseVoxlabComponent;
    readonly environment: BaseVoxlabComponent;
    readonly toneExposure: BaseVoxlabComponent;
    readonly shading: BaseVoxlabComponent;
    readonly shadows: BaseVoxlabComponent;
    readonly hemisphere: BaseVoxlabComponent;
    readonly ambient: BaseVoxlabComponent;
    readonly keyLight: BaseVoxlabComponent;
    readonly fillLight: BaseVoxlabComponent;
    readonly rimLight: BaseVoxlabComponent;
    readonly topLight: BaseVoxlabComponent;
    readonly bottomLight: BaseVoxlabComponent;
    readonly parts: BaseVoxlabComponent;
    readonly paint: BaseVoxlabComponent;
    readonly gradient: BaseVoxlabComponent;
    readonly albedo: BaseVoxlabComponent;
    readonly pbrMaps: BaseVoxlabComponent;
    readonly pbrGeneration: BaseVoxlabComponent;
}
