import { DEFAULT_LIGHTING as _DEFAULT_LIGHTING } from "./default-lighting.js";
export const DEFAULT_LIGHTING = _DEFAULT_LIGHTING;
import {
    DEFAULT_ENVIRONMENT as _DEFAULT_ENVIRONMENT,
    DEFAULT_HEMISPHERE as _DEFAULT_HEMISPHERE,
    ENV_INTENSITY_MAX as _ENV_INTENSITY_MAX,
} from "./default-environment.js";
export const DEFAULT_ENVIRONMENT = _DEFAULT_ENVIRONMENT;
export const DEFAULT_HEMISPHERE = _DEFAULT_HEMISPHERE;
export const ENV_INTENSITY_MAX = _ENV_INTENSITY_MAX;
import {
    DEFAULT_BOTTOM_LIGHT as _DEFAULT_BOTTOM_LIGHT,
    DEFAULT_RIM_LIGHT as _DEFAULT_RIM_LIGHT,
    DEFAULT_TOP_LIGHT as _DEFAULT_TOP_LIGHT,
} from "./default-aux-lights.js";
export const DEFAULT_BOTTOM_LIGHT = _DEFAULT_BOTTOM_LIGHT;
export const DEFAULT_RIM_LIGHT = _DEFAULT_RIM_LIGHT;
export const DEFAULT_TOP_LIGHT = _DEFAULT_TOP_LIGHT;
export {
    LIGHT_INTENSITY_MAX,
    LIGHT_POSITION_MAX,
    LIGHT_POSITION_MIN,
    SHADOW_BIAS_MAX,
    SHADOW_BIAS_MIN,
    SHADOW_RADIUS_MAX,
    SHADOW_RADIUS_MIN,
} from "./light-ranges.js";
export {
    DEFAULT_SHADOW_NORMAL_BIAS,
    SHADOW_CAMERA_FAR,
    SHADOW_CAMERA_HALF_EXTENT,
    SHADOW_CAMERA_NEAR,
    SHADOW_MAP_SIZE,
} from "./shadow-camera.js";
