export interface ConditionField {
    field: string;
    label: string;
}

const CONDITION_FIELDS_BY_TRIGGER: Record<string, readonly ConditionField[]> = {
    level_up: [
        { field: "rsn", label: "RSN" },
        { field: "accountType", label: "Type" },
        { field: "skill", label: "Skill" },
        { field: "level", label: "New level" },
    ],
    death: [
        { field: "rsn", label: "RSN" },
        { field: "causeName", label: "Cause" },
        { field: "causeCategory", label: "Cause category" },
        { field: "causeKind", label: "Cause kind" },
        { field: "regionName", label: "Region" },
        { field: "area", label: "Area" },
    ],
    slayer: [
        { field: "rsn", label: "RSN" },
        { field: "targetName", label: "Task target" },
        { field: "masterName", label: "Slayer master" },
        { field: "bossName", label: "Boss" },
        { field: "areaName", label: "Slayer area" },
        { field: "count", label: "Remaining" },
        { field: "countOriginal", label: "Original count" },
    ],
    loot: [
        { field: "rsn", label: "RSN" },
        { field: "source", label: "Source NPC/item" },
        { field: "causeKind", label: "Cause kind" },
        { field: "items", label: "Item" },
        { field: "regionName", label: "Region" },
        { field: "gp", label: "Total GP" },
        { field: "kc", label: "Kill count" },
        { field: "sourceLevel", label: "Source level" },
    ],
    pet_drop: [
        { field: "rsn", label: "RSN" },
        { field: "petName", label: "Pet name" },
        { field: "trigger", label: "Trigger source" },
        { field: "source", label: "Source NPC" },
        { field: "sourceKind", label: "Source kind" },
        { field: "regionName", label: "Region" },
    ],
    bank_close: [
        { field: "rsn", label: "RSN" },
        { field: "itemCount", label: "Item count" },
    ],
    quests: [
        { field: "rsn", label: "RSN" },
        { field: "completed", label: "Completed" },
        { field: "total", label: "Total" },
    ],
    quest_completed: [
        { field: "rsn", label: "RSN" },
        { field: "name", label: "Quest name" },
        { field: "status", label: "Status" },
    ],
    diaries: [
        { field: "rsn", label: "RSN" },
        { field: "completed", label: "Completed" },
        { field: "total", label: "Total" },
    ],
    diary_completed: [
        { field: "rsn", label: "RSN" },
        { field: "name", label: "Diary name" },
        { field: "region", label: "Region" },
        { field: "tier", label: "Tier" },
    ],
    clue_completed: [
        { field: "rsn", label: "RSN" },
        { field: "tier", label: "Tier" },
        { field: "total", label: "Total" },
    ],
    collection_log_entry: [
        { field: "rsn", label: "RSN" },
        { field: "itemName", label: "Item name" },
        { field: "category", label: "Category" },
    ],
    collection_log_snapshot: [
        { field: "rsn", label: "RSN" },
        { field: "itemCount", label: "Item count" },
    ],
    combat_achievement_completed: [
        { field: "rsn", label: "RSN" },
        { field: "name", label: "CA name" },
        { field: "bossName", label: "Boss" },
        { field: "taskType", label: "Task type" },
        { field: "tier", label: "Tier" },
        { field: "points", label: "Points" },
    ],
    combat_achievements_snapshot: [
        { field: "rsn", label: "RSN" },
        { field: "totalCompleted", label: "Total completed" },
    ],
    menu_action: [
        { field: "rsn", label: "RSN" },
        { field: "action", label: "Action" },
        { field: "option", label: "Option" },
        { field: "target", label: "Target" },
    ],
    farming_patch: [
        { field: "rsn", label: "RSN" },
        { field: "patchRegionName", label: "Patch region" },
        { field: "cropName", label: "Crop" },
        { field: "state", label: "State" },
        { field: "value", label: "Varbit value" },
    ],
    clan_chat: [
        { field: "rsn", label: "RSN" },
        { field: "accountType", label: "Type" },
        { field: "rank", label: "Rank" },
        { field: "message", label: "Message" },
    ],
};

const ENTITY_FIELDS: readonly ConditionField[] = [
    { field: "entity.rsn", label: "Member RSN" },
    { field: "entity.account.type", label: "Account type" },
    { field: "entity.skills.total_level", label: "Total level" },
    { field: "entity.clan.rank", label: "Clan rank" },
    { field: "entity.clan.tenure_days", label: "Tenure (days)" },
    { field: "entity.recent.days_inactive", label: "Days inactive" },
];

const FLOW_BUILDER_FIELDS_BY_TRIGGER: Record<string, readonly ConditionField[]> = {
    "discord:channels.created": [...ENTITY_FIELDS, { field: "channel.name", label: "Channel name" }, { field: "channel.type", label: "Channel type" }, { field: "channel.parent_id", label: "Parent category id" }],
    "discord:channels.updated": [...ENTITY_FIELDS, { field: "channel.name", label: "Channel name" }, { field: "channel.type", label: "Channel type" }],
    "discord:channels.deleted": [...ENTITY_FIELDS, { field: "channel.name", label: "Channel name" }, { field: "channel.type", label: "Channel type" }],
    "discord:members.joined": [...ENTITY_FIELDS, { field: "member.id", label: "Member id" }],
    "discord:members.left": [...ENTITY_FIELDS, { field: "member.id", label: "Member id" }],
    "discord:members.banned": [...ENTITY_FIELDS, { field: "member.id", label: "Member id" }, { field: "reason", label: "Ban reason" }],
    "discord:roles.created": [...ENTITY_FIELDS, { field: "role.name", label: "Role name" }],
    "discord:roles.assigned": [...ENTITY_FIELDS, { field: "role.name", label: "Role name" }, { field: "member.id", label: "Member id" }],
    "discord:roles.removed": [...ENTITY_FIELDS, { field: "role.name", label: "Role name" }, { field: "member.id", label: "Member id" }],
    "discord:messages.reacted": [...ENTITY_FIELDS, { field: "reaction.emoji", label: "Reaction emoji" }, { field: "channel.name", label: "Channel name" }],
    "discord:voice.joined": [...ENTITY_FIELDS, { field: "channel.name", label: "Voice channel" }],
    "discord:voice.left": [...ENTITY_FIELDS, { field: "channel.name", label: "Voice channel" }],
    "discord:threads.created": [...ENTITY_FIELDS, { field: "thread.name", label: "Thread name" }, { field: "channel.name", label: "Parent channel" }],
    "discord:events.started": [...ENTITY_FIELDS, { field: "event.name", label: "Event name" }],
    "plugin:skillReached": [...ENTITY_FIELDS, { field: "skill", label: "Skill" }, { field: "level", label: "Level" }, { field: "prior_level", label: "Prior level" }, { field: "xp_total", label: "Total XP" }],
    "plugin:skillReached99": [...ENTITY_FIELDS, { field: "skill", label: "Skill" }, { field: "xp_total", label: "Total XP" }],
    "plugin:skillReached200m": [...ENTITY_FIELDS, { field: "skill", label: "Skill" }],
    "plugin:maxLevelReached": [...ENTITY_FIELDS],
    "plugin:bossKilled": [...ENTITY_FIELDS, { field: "boss", label: "Boss" }, { field: "kc", label: "Kill count" }, { field: "party_rsns", label: "Party RSNs" }, { field: "time", label: "Kill time" }, { field: "value", label: "Loot value" }],
    "plugin:firstKill": [...ENTITY_FIELDS, { field: "boss", label: "Boss" }],
    "plugin:kcMilestone": [...ENTITY_FIELDS, { field: "boss", label: "Boss" }, { field: "kc", label: "Kill count" }],
    "plugin:dropObtained": [...ENTITY_FIELDS, { field: "boss", label: "Boss" }, { field: "item", label: "Item" }, { field: "value", label: "GP value" }, { field: "rarity_one_in_n", label: "Rarity 1/N" }],
    "plugin:rareDropObtained": [...ENTITY_FIELDS, { field: "boss", label: "Boss" }, { field: "item", label: "Item" }, { field: "value", label: "GP value" }, { field: "rarity_one_in_n", label: "Rarity 1/N" }],
    "plugin:petObtained": [...ENTITY_FIELDS, { field: "boss", label: "Source" }, { field: "kc", label: "Kill count" }],
    "plugin:collectionLogSlot": [...ENTITY_FIELDS, { field: "section", label: "Section" }, { field: "slot_count", label: "Slot count" }, { field: "slots_total", label: "Slots total" }],
    "plugin:clueCompleted": [...ENTITY_FIELDS, { field: "tier", label: "Tier" }, { field: "kc", label: "Total cluescroll KC" }, { field: "rewards_value", label: "Rewards value" }],
    "plugin:diaryCompleted": [...ENTITY_FIELDS, { field: "region", label: "Region" }, { field: "tier", label: "Tier" }],
    "plugin:combatAchievementUnlocked": [...ENTITY_FIELDS, { field: "tier", label: "Tier" }, { field: "points", label: "Points" }],
    "plugin:questCompleted": [...ENTITY_FIELDS, { field: "name", label: "Quest name" }],
    "plugin:questCape": [...ENTITY_FIELDS],
    "plugin:maxCape": [...ENTITY_FIELDS],
    "plugin:raidCompleted": [...ENTITY_FIELDS, { field: "raid", label: "Raid" }, { field: "time", label: "Time" }, { field: "deaths", label: "Deaths" }, { field: "party_rsns", label: "Party RSNs" }, { field: "splits_gp", label: "GP split" }],
    "plugin:personalBest": [...ENTITY_FIELDS, { field: "activity", label: "Activity" }, { field: "time", label: "Time" }, { field: "improvement_pct", label: "Improvement %" }],
    "plugin:deathOccurred": [...ENTITY_FIELDS, { field: "death_location", label: "Death location" }, { field: "in_wilderness", label: "In wilderness" }, { field: "death_cause", label: "Death cause" }, { field: "attacker_rsn", label: "Attacker RSN" }, { field: "value_lost", label: "Value lost" }, { field: "world", label: "World" }],
    "plugin:tradeCompleted": [...ENTITY_FIELDS, { field: "partner_rsn", label: "Partner RSN" }, { field: "value", label: "Trade value" }],
    "plugin:loginDetected": [...ENTITY_FIELDS, { field: "world", label: "World" }],
    "plugin:logoutDetected": [...ENTITY_FIELDS, { field: "world", label: "World" }],
    "plugin:screenshotPosted": [...ENTITY_FIELDS, { field: "channel", label: "Channel" }],
    "wom:competitionStarted": [...ENTITY_FIELDS, { field: "competition", label: "Competition" }, { field: "metric", label: "Metric" }],
    "wom:competitionEnded": [...ENTITY_FIELDS, { field: "competition", label: "Competition" }, { field: "metric", label: "Metric" }, { field: "top_three", label: "Top three" }, { field: "top_gain", label: "Top gain" }],
    "wom:hiscoreRankChanged": [...ENTITY_FIELDS, { field: "metric", label: "Metric" }, { field: "prior_rank", label: "Prior rank" }, { field: "new_rank", label: "New rank" }, { field: "delta", label: "Rank delta" }],
    "wom:groupUpdated": [...ENTITY_FIELDS],
    "clansocket:memberAddedToClan": [...ENTITY_FIELDS, { field: "rank", label: "Initial rank" }],
    "clansocket:memberLeftClan": [...ENTITY_FIELDS, { field: "days_tenure", label: "Days tenure" }],
    "clansocket:memberRankPromoted": [...ENTITY_FIELDS, { field: "prior_rank", label: "Prior rank" }, { field: "new_rank", label: "New rank" }],
    "clansocket:memberRankDemoted": [...ENTITY_FIELDS, { field: "prior_rank", label: "Prior rank" }, { field: "new_rank", label: "New rank" }],
    "clansocket:memberWentInactive": [...ENTITY_FIELDS, { field: "days_inactive", label: "Days inactive" }, { field: "threshold_days", label: "Threshold" }],
    "clansocket:memberReturned": [...ENTITY_FIELDS, { field: "days_away", label: "Days away" }],
    "clansocket:clanTenureMilestone": [...ENTITY_FIELDS, { field: "threshold_days", label: "Threshold (days)" }],
    "clansocket:clanEventScheduled": [...ENTITY_FIELDS, { field: "event_id", label: "Event id" }],
    "clansocket:clanEventStarted": [...ENTITY_FIELDS, { field: "event_id", label: "Event id" }],
    "clansocket:clanEventEnded": [...ENTITY_FIELDS, { field: "event_id", label: "Event id" }],
    "clansocket:rsvpReceived": [...ENTITY_FIELDS, { field: "event_id", label: "Event id" }, { field: "response", label: "Response" }],
};

export function fieldsForTrigger(triggerType: string): readonly ConditionField[] {
    return CONDITION_FIELDS_BY_TRIGGER[triggerType] ?? FLOW_BUILDER_FIELDS_BY_TRIGGER[triggerType] ?? [];
}
