export const PERMISSION_FLAG_NAMES: readonly string[] = [
    "CreateInstantInvite",
    "KickMembers",
    "BanMembers",
    "Administrator",
    "ManageChannels",
    "ManageGuild",
    "AddReactions",
    "ViewAuditLog",
    "PrioritySpeaker",
    "Stream",
    "ViewChannel",
    "SendMessages",
    "SendTTSMessages",
    "ManageMessages",
    "EmbedLinks",
    "AttachFiles",
    "ReadMessageHistory",
    "MentionEveryone",
    "UseExternalEmojis",
    "ViewGuildInsights",
    "Connect",
    "Speak",
    "MuteMembers",
    "DeafenMembers",
    "MoveMembers",
    "UseVAD",
    "ChangeNickname",
    "ManageNicknames",
    "ManageRoles",
    "ManageWebhooks",
    "ManageGuildExpressions",
    "UseApplicationCommands",
    "RequestToSpeak",
    "ManageEvents",
    "ManageThreads",
    "CreatePublicThreads",
    "CreatePrivateThreads",
    "UseExternalStickers",
    "SendMessagesInThreads",
    "UseEmbeddedActivities",
    "ModerateMembers",
    "ViewCreatorMonetizationAnalytics",
    "UseSoundboard",
    "CreateGuildExpressions",
    "CreateEvents",
    "UseExternalSounds",
    "SendVoiceMessages",
];

export const PERMISSION_STATE_ALLOW = "allow";
export const PERMISSION_STATE_DENY = "deny";
export const PERMISSION_STATE_INHERIT = "inherit";

export const PERMISSION_BIT_BY_NAME: ReadonlyMap<string, number> = new Map(
    PERMISSION_FLAG_NAMES.map((name, i) => [name, i]),
);
