export const TRIGGER_LABELS: Record<string, string> = {
    level_up: "Level up",
    death: "Death",
    slayer: "Slayer task tick",
    loot: "Loot drop",
    pet_drop: "Pet drop",
    bank_close: "Bank closed",
    quests: "Quests (rollup)",
    quest_completed: "Quest completed",
    diaries: "Diaries (rollup)",
    diary_completed: "Diary tier completed",
    clue_completed: "Clue completed",
    collection_log_entry: "Collection log unlock",
    collection_log_snapshot: "Collection log snapshot",
    combat_achievement_completed: "Combat achievement completed",
    combat_achievements_snapshot: "Combat achievements snapshot",
    menu_action: "Menu action",
    farming_patch: "Farming patch",
    clan_chat: "Clan chat message",
    runewatch_hard_added: "RuneWatch flag added (hard)",
    runewatch_hard_cleared: "RuneWatch flag cleared (hard)",
    runewatch_soft_added: "WDR report added (soft)",
    runewatch_soft_cleared: "WDR report withdrawn (soft)",
};

export const DEFAULT_CONTENT_TEMPLATE_BY_TRIGGER: Record<string, string> = {
    level_up: "**`{rsn}`** reached level `{level}` in `{skill}`",
    death: "**`{rsn}`** died",
    slayer: "**`{rsn}`** `{count}/{countOriginal}` **`{targetName}'s`** remaining",
    loot: "**`{rsn}`** received {items} - Worth **`{gp} gp`**",
    pet_drop: "**`{rsn}`** got a pet (**`{trigger}`**)",
    bank_close: "**`{rsn}`** closed bank",
    quests: "**`{rsn}`** `{completed}/{total}` finished",
    quest_completed: "**`{rsn}`** completed",
    diaries: "**`{rsn}`** `{completed}/{total}` complete",
    diary_completed: "**`{rsn}`** completed",
    clue_completed: "**`{rsn}`** completed (total `{total}`)",
    collection_log_entry: "**`{rsn}`** unlocked **[{itemName}]({wikiLink})**",
    collection_log_snapshot: "**`{rsn}`** `{itemCount}` items unlocked",
    combat_achievement_completed: "**`{rsn}`** completed (**`{tier}`**, `{points} pts`)",
    combat_achievements_snapshot: "**`{rsn}`** `{totalCompleted}` completed",
    menu_action: "**`{rsn}`** {action} {option} {target}",
    farming_patch: "**`{rsn}`** varbit `{varbitId}` = `{value}`",
    clan_chat: "{message}",
    runewatch_hard_added:
        "A clan member **`{rsn}`** has been placed on the runewatch list — case `{hash}`, *{reason}*, evidence `{evidence_rating}/5`. Their data is being purged from clansocket.",
    runewatch_hard_cleared:
        "A clan member **`{rsn}`** has been removed from the runewatch list — case `{hash}` resolved. They can now verify with clansocket again.",
    runewatch_soft_added:
        "A clan member **`{rsn}`** has been reported on WDR for: *{reason}*. This is an unvetted community submission — no action taken, advisory only.",
    runewatch_soft_cleared: "A WDR report against **`{rsn}`** has been withdrawn.",
};
