import { SQL_COLUMNS } from "../../../database/core/sql-columns.js";

export const GLOBAL_SECRET_COLUMNS: readonly string[] = [
    SQL_COLUMNS.ACCOUNT_HASH,
    "target_account_hash",
    "declared_account_hash",
    "owner_account_hash",
    "captured_by_account_hash",
    SQL_COLUMNS.SITE_ACCOUNT_ID,
    "requesting_site_account_id",
    "actor_site_account_id",
    "owner_site_account_id",
    "redeemed_by_site_account_id",
    "created_by_site_account_id",
    "provider_user_id",
    "credential_id",
    "user_id",
    "fingerprint",
    "from_fingerprint",
    "to_fingerprint",
    "target_id",
    "payload",
    "payload_json",
];

export const READ_ONLY_BROWSE_TABLES: ReadonlySet<string> = new Set([
    "clansocket_data_action_log",
    "clan_audit_log",
    "discord_servers",
    "discord_bot_identities",
    "discord_webhook_tokens",
    "clansocket_oauth_sessions",
    "clansocket_webauthn_challenges",
    "clansocket_passkeys",
    "clansocket_backup_codes",
    "clansocket_device_link_codes",
    "clansocket_accounts",
    "clansocket_account_bindings",
    "clansocket_account_rsns",
    "clansocket_account_providers",
    "clansocket_clans",
    "clansocket_clan_managers",
    "clansocket_clan_manager_requests",
    "clansocket_clan_whitelists",
    "clansocket_consent_requests",
    "clan_settings",
    "clan_eligibility_rules",
    "clan_rosters",
]);
