import { SQL_COLUMNS, SQL_TABLES } from "../../../database/core/sql-columns.js";

export const GLOBAL_SECRET_COLUMNS: readonly string[] = [
    SQL_COLUMNS.ACCOUNT_HASH,
    "target_account_hash",
    "declared_account_hash",
    "owner_account_hash",
    "captured_by_account_hash",
    SQL_COLUMNS.SITE_ACCOUNT_ID,
    "requesting_site_account_id",
    "actor_site_account_id",
    "owner_site_account_id",
    "redeemed_by_site_account_id",
    "created_by_site_account_id",
    "provider_user_id",
    "credential_id",
    "user_id",
    "fingerprint",
    "from_fingerprint",
    "to_fingerprint",
    "target_id",
    "payload",
    "payload_json",
];

export const READ_ONLY_BROWSE_TABLES: ReadonlySet<string> = new Set([
    SQL_TABLES.CLANSOCKET_DATA_ACTION_LOG,
    "clan_audit_log",
    SQL_TABLES.DISCORD_SERVERS,
    SQL_TABLES.DISCORD_BOT_IDENTITIES,
    "discord_webhook_tokens",
    SQL_TABLES.CLANSOCKET_OAUTH_SESSIONS,
    SQL_TABLES.CLANSOCKET_WEBAUTHN_CHALLENGES,
    SQL_TABLES.CLANSOCKET_PASSKEYS,
    SQL_TABLES.CLANSOCKET_BACKUP_CODES,
    SQL_TABLES.CLANSOCKET_DEVICE_LINK_CODES,
    SQL_TABLES.CLANSOCKET_ACCOUNTS,
    SQL_TABLES.CLANSOCKET_ACCOUNT_BINDINGS,
    SQL_TABLES.CLANSOCKET_ACCOUNT_RSNS,
    SQL_TABLES.CLANSOCKET_ACCOUNT_PROVIDERS,
    SQL_TABLES.CLANSOCKET_CLANS,
    SQL_TABLES.CLANSOCKET_CLAN_MANAGERS,
    SQL_TABLES.CLANSOCKET_CLAN_MANAGER_REQUESTS,
    SQL_TABLES.CLANSOCKET_CLAN_WHITELISTS,
    SQL_TABLES.CLANSOCKET_CONSENT_REQUESTS,
    "clan_settings",
    "clan_eligibility_rules",
    SQL_TABLES.CLAN_ROSTERS,
]);
