import type { ApplyCtx as _ApplyCtx } from "./apply/apply-ctx.js";
export type ApplyCtx = _ApplyCtx;
import { requireColorAttribute as _requireColorAttribute } from "./apply/apply-ctx.js";
export const requireColorAttribute = _requireColorAttribute;
import { applyAllPaint as _applyAllPaint, fillPartBuffer as _fillPartBuffer } from "./apply/apply-all-paint.js";
export const applyAllPaint = _applyAllPaint;
export const fillPartBuffer = _fillPartBuffer;
import { applyPartial as _applyPartial } from "./apply/apply-partial.js";
export const applyPartial = _applyPartial;
import { computeRange as _computeRange } from "./apply/apply-compute-range.js";
export const computeRange = _computeRange;
