import type { BuildMeshOpts as _BuildMeshOpts } from "./mesh-build.js";
export type BuildMeshOpts = _BuildMeshOpts;
import { buildMesh as _buildMesh } from "./mesh-build.js";
export const buildMesh = _buildMesh;
import { createMaterialsVariant as _createMaterialsVariant } from "./mesh-materials.js";
export const createMaterialsVariant = _createMaterialsVariant;
import { disposeMesh as _disposeMesh } from "./mesh-dispose.js";
export const disposeMesh = _disposeMesh;
import { setShadingMode as _setShadingMode } from "./mesh-shading.js";
export const setShadingMode = _setShadingMode;
import { exportPainted as _exportPainted } from "./mesh-export-painted.js";
export const exportPainted = _exportPainted;
