const IDLE_PHRASES = [
    "Parsing the drop table...",
    "Noted. Unnoting response...",
    "Tick-manipulating a reply...",
    "1-ticking the lookup...",
    "Prayer flicking through context...",
    "Spec tabbing the database...",
    "3rd age drop rate on this query...",
    "Splashing on the first attempt...",
    "Pathing through the render queue...",
    "Constructing a response (83 con btw)...",
    "Decanting your request into doses...",
    "Hopping worlds for a free server...",
    "Grinding the query slayer task...",
    "Loot tab building in progress...",
    "Rolling the RDT for your answer...",
    "Pulling data from the collection log...",
    "Tagging tiles on the response path...",
    "Overloading the context buffer...",
    "De-ironing this dataset...",
    "Telegrabbing from the cache...",
    "Venging the last failed parse...",
    "Safespot found. Ranging the DB...",
    "Flinching this query one tick at a time...",
    "Banking before the next pull...",
    "Flicking rigour on the lookup...",
    "This is an efficient grind, trust...",
    "Thieving XP from the response pipeline...",
    "Runecrafting through pure pain...",
    "Doing a farm run on the tables...",
    "Boosting +5 for this query...",
    "Trimming your query for free...",
    "Dancing for data plox...",
    "Buying gf for 10k context tokens...",
    "Doubling your response, trade me...",
    "Following Zezima to the answer...",
    "Falador massacre on stale cache...",
    "Connection lost. Reconnecting...",
    "Sit. Get parsed.",
    "Swapping to w302 for GE lookup...",
    "Nice.",
    "Meet me at Varrock wildy wall...",
    "Drop party in the context window...",
    "Reported for bug abuse (minor)...",
    "Gnome child is thinking...",
    "Sea shanty 2 playing internally...",
    "Flash2:wave: loading response...",
    "Spinning flax into an answer...",
    "Selling lobbies 250 ea...",
    "Red:shake: computing results...",
    "Doing Mourning's End Pt 2 rn...",
    "73.",
    "Ags to gmaul combo on this parse...",
    "Cyan:scroll: fetching from DB...",
    "Lighting logs to Lumbridge...",
    "Rendi would be proud of this skip...",
    "B0aty would RC for this answer...",
    "Woox would walk this query...",
    "Authenticator delay on the response...",
    "Skull tricked into a chain turn...",
    "Pulling a Settled and limiting myself...",
    "Draining prayer points per token...",
];

export { IDLE_PHRASES };
