import type { ProduceKey, ProduceInfo } from "./types.ts";

export const PRODUCE: Readonly<Record<ProduceKey, ProduceInfo>> = {
    WEEDS: { name: "Weeds", itemId: 6055 },
    SCARECROW: { name: "Scarecrow", itemId: 6059 },
    POTATO: { name: "Potato", itemId: 1942 },
    ONION: { name: "Onion", itemId: 1957 },
    CABBAGE: { name: "Cabbage", itemId: 1965 },
    TOMATO: { name: "Tomato", itemId: 1982 },
    SWEETCORN: { name: "Sweetcorn", itemId: 5986 },
    STRAWBERRY: { name: "Strawberry", itemId: 5504 },
    WATERMELON: { name: "Watermelon", itemId: 5982 },
    SNAPE_GRASS: { name: "Snape grass", itemId: 231 },
    MARIGOLD: { name: "Marigold", itemId: 6010 },
    ROSEMARY: { name: "Rosemary", itemId: 6014 },
    NASTURTIUM: { name: "Nasturtium", itemId: 6012 },
    WOAD: { name: "Woad", itemId: 1793 },
    LIMPWURT: { name: "Limpwurt", itemId: 225 },
    WHITE_LILY: { name: "White lily", itemId: 22932 },
    REDBERRIES: { name: "Redberry", itemId: 1951 },
    CADAVABERRIES: { name: "Cadavaberry", itemId: 753 },
    DWELLBERRIES: { name: "Dwellberry", itemId: 2126 },
    JANGERBERRIES: { name: "Jangerberry", itemId: 247 },
    WHITEBERRIES: { name: "Whiteberry", itemId: 239 },
    POISON_IVY: { name: "Poison ivy", itemId: 6018 },
    BARLEY: { name: "Barley", itemId: 6006 },
    HAMMERSTONE: { name: "Hammerstone", itemId: 5994 },
    ASGARNIAN: { name: "Asgarnian", itemId: 5996 },
    JUTE: { name: "Jute", itemId: 5931 },
    YANILLIAN: { name: "Yanillian", itemId: 5998 },
    FLAX: { name: "Flax", itemId: 1779 },
    KRANDORIAN: { name: "Krandorian", itemId: 6000 },
    WILDBLOOD: { name: "Wildblood", itemId: 6002 },
    HEMP: { name: "Hemp", itemId: 31457 },
    COTTON: { name: "Cotton", itemId: 31460 },
    GUAM: { name: "Guam", itemId: 249 },
    MARRENTILL: { name: "Marrentill", itemId: 251 },
    TARROMIN: { name: "Tarromin", itemId: 253 },
    HARRALANDER: { name: "Harralander", itemId: 255 },
    RANARR: { name: "Ranarr", itemId: 257 },
    TOADFLAX: { name: "Toadflax", itemId: 2998 },
    IRIT: { name: "Irit", itemId: 259 },
    AVANTOE: { name: "Avantoe", itemId: 261 },
    KWUARM: { name: "Kwuarm", itemId: 263 },
    HUASCA: { name: "Huasca", itemId: 30097 },
    SNAPDRAGON: { name: "Snapdragon", itemId: 3000 },
    CADANTINE: { name: "Cadantine", itemId: 265 },
    LANTADYME: { name: "Lantadyme", itemId: 2481 },
    DWARF_WEED: { name: "Dwarf weed", itemId: 267 },
    TORSTOL: { name: "Torstol", itemId: 269 },
    GOUTWEED: { name: "Goutweed", itemId: 3261 },
    ANYHERB: { name: "Any herb", itemId: 249 },
    OAK: { name: "Oak", itemId: 1521 },
    WILLOW: { name: "Willow", itemId: 1519 },
    MAPLE: { name: "Maple", itemId: 1517 },
    YEW: { name: "Yew", itemId: 1515 },
    MAGIC: { name: "Magic", itemId: 1513 },
    APPLE: { name: "Apple", itemId: 1955 },
    BANANA: { name: "Banana", itemId: 1963 },
    ORANGE: { name: "Orange", itemId: 2108 },
    CURRY: { name: "Curry", itemId: 5970 },
    PINEAPPLE: { name: "Pineapple", itemId: 2114 },
    PAPAYA: { name: "Papaya", itemId: 5972 },
    PALM: { name: "Palm", itemId: 5974 },
    DRAGONFRUIT: { name: "Dragonfruit", itemId: 22929 },
    CACTUS: { name: "Cactus", itemId: 6016 },
    POTATO_CACTUS: { name: "Potato cactus", itemId: 3138 },
    TEAK: { name: "Teak", itemId: 6333 },
    MAHOGANY: { name: "Mahogany", itemId: 6332 },
    CAMPHOR: { name: "Camphor", itemId: 32904 },
    IRONWOOD: { name: "Ironwood", itemId: 32907 },
    ROSEWOOD: { name: "Rosewood", itemId: 32910 },
    ATTAS: { name: "Attas", itemId: 22940 },
    IASOR: { name: "Iasor", itemId: 22939 },
    KRONOS: { name: "Kronos", itemId: 22938 },
    ELKHORN_CORAL: { name: "Elkhorn", itemId: 31481 },
    PILLAR_CORAL: { name: "Pillar", itemId: 31484 },
    UMBRAL_CORAL: { name: "Umbral", itemId: 31487 },
    SEAWEED: { name: "Seaweed", itemId: 21504 },
    GRAPE: { name: "Grape", itemId: 1987 },
    MUSHROOM: { name: "Mushroom", itemId: 6004 },
    BELLADONNA: { name: "Belladonna", itemId: 2398 },
    CALQUAT: { name: "Calquat", itemId: 5980 },
    SPIRIT_TREE: { name: "Spirit tree", itemId: 6063 },
    CELASTRUS: { name: "Celastrus", itemId: 1391 },
    REDWOOD: { name: "Redwood", itemId: 19669 },
    HESPORI: { name: "Hespori", itemId: 23044 },
    CRYSTAL_TREE: { name: "Crystal tree", itemId: 23866 },
    EMPTY_COMPOST_BIN: { name: "Compost Bin", itemId: 3271 },
    COMPOST: { name: "Compost", itemId: 6032 },
    SUPERCOMPOST: { name: "Supercompost", itemId: 6034 },
    ULTRACOMPOST: { name: "Ultracompost", itemId: 21483 },
    ROTTEN_TOMATO: { name: "Rotten Tomato", itemId: 2518 },
    EMPTY_BIG_COMPOST_BIN: { name: "Big Compost Bin", itemId: 3271 },
    BIG_COMPOST: { name: "Compost", itemId: 6032 },
    BIG_SUPERCOMPOST: { name: "Supercompost", itemId: 6034 },
    BIG_ULTRACOMPOST: { name: "Ultracompost", itemId: 21483 },
    BIG_ROTTEN_TOMATO: { name: "Rotten Tomato", itemId: 2518 },
};
