export const PH_CHAIN_AUTO_LIMIT = "{{AI_CHAIN_AUTO_LIMIT}}";
export const PH_CHAIN_AUTO_LIMIT_WARN_AT = "{{AI_CHAIN_AUTO_LIMIT_WARN_AT}}";
export const PH_POLL_MIN_SECONDS = "{{AI_POLL_MIN_SECONDS}}";
export const PH_POLL_MAX_SECONDS = "{{AI_POLL_MAX_SECONDS}}";
export const PH_HISTORY_WINDOW = "{{AI_HISTORY_WINDOW}}";
