export const MARKER_DOM_ACTION_RESULTS = "[DOM ACTION RESULTS]";
export const MARKER_USER_LOCAL_TIME = "[USER LOCAL TIME: <local clock + tz>]";
export const MARKER_USER_APPENDED_MID_CHAIN = "[USER APPENDED MID-CHAIN]";
export const MARKER_PAGE_STATE_UPDATED = "[PAGE STATE UPDATED]";
export const MARKER_PRIOR_CHAIN = "[PRIOR CHAIN: chain-<id>]";
export const MARKER_AUTO_LIMIT_REACHED = "[AUTO-LIMIT REACHED]";
