export const ARIA_PROP_TO_ATTR: Record<string, string> = {
    ariaLabel: "aria-label",
    ariaLabelledby: "aria-labelledby",
    ariaDescribedby: "aria-describedby",
    ariaHidden: "aria-hidden",
    ariaPressed: "aria-pressed",
    ariaSelected: "aria-selected",
    ariaExpanded: "aria-expanded",
    ariaControls: "aria-controls",
    ariaModal: "aria-modal",
    ariaLive: "aria-live",
    ariaCurrent: "aria-current",
    ariaInvalid: "aria-invalid",
    ariaRequired: "aria-required",
    ariaChecked: "aria-checked",
    ariaBusy: "aria-busy",
    ariaAtomic: "aria-atomic",
    ariaHaspopup: "aria-haspopup",
    ariaOrientation: "aria-orientation",
};

export const HTML_ATTR_PROPS = [
    "id",
    "type",
    "name",
    "value",
    "placeholder",
    "disabled",
    "readonly",
    "required",
    "checked",
    "hidden",
    "min",
    "max",
    "step",
    "pattern",
    "maxlength",
    "minlength",
    "autocomplete",
    "inputmode",
    "rows",
    "cols",
    "href",
    "download",
    "target",
    "rel",
    "src",
    "alt",
    "width",
    "height",
    "for",
    "role",
    "tabindex",
    "title",
    "open",
    "multiple",
    "selected",
    "spellcheck",
    "contenteditable",
    "draggable",
    "form",
    "accept",
    "style",
] as const;
