import { LIGHT, MEME, SERIOUS, type QuipSet } from "./core/quip-types.js";
import { q } from "./core/factories/quip-factory.js";

export const AUTH_QUIPS: QuipSet = [
    q(SERIOUS, "Hi, varez here. I only chat with registered ClanSocket members. Consider joining us?"),
    q(SERIOUS, "Sorry, ClanSocket-only bot. Get authenticated and we'll talk."),
    q(SERIOUS, "AI access is for registered ClanSocket users only. Use the buttons below to sign up."),
    q(SERIOUS, "Varez can only assist verified ClanSocket community members."),
    q(SERIOUS, "You're not in the ClanSocket member list. Sign up with GitHub, Discord or a passkey to continue."),

    q(LIGHT, "Varez doesn't trust strangers in the Wildy. Get a clan vouch or stay safe in Edgeville."),
    q(LIGHT, "You don't meet the quest requirements. Complete 'Join the ClanSocket Community' to continue."),
    q(LIGHT, "No sign-in, no conversation. That's the rule, sorry."),
    q(LIGHT, "Varez is at the bank. Sign in and he might reply."),
    q(LIGHT, "Varez only replies to mutuals. Sign in below and we'll mutual up."),
    q(LIGHT, "Varez checked his friends list. You're not on it. Register to fix that."),
    q(LIGHT, "Varez is busy AFKing at the GE. Come back once you're signed in."),
    q(LIGHT, "Tutorial Island called. You're not done yet. Register to finish the tutorial."),
    q(LIGHT, "Varez is deep in a farm run and can't be disturbed by randos. Sign in below for VIP access."),
    q(LIGHT, "Your name isn't on the ClanSocket guest list. Sign up and we'll add it."),
    q(LIGHT, "Varez is a members' world bot. Use the buttons below to step through the gate."),
    q(LIGHT, "Varez only responds to signed-in ClanSocket users. Let's fix that."),
    q(LIGHT, "Varez has his private chat set to friends-only. Sign in below to get added."),
    q(LIGHT, "Varez is set to 'busy' for non-members. Register to bump yourself up the queue."),
    q(LIGHT, "Varez is auto-kicking non-members from his CC. Register to stay in."),

    q(
        MEME,
        "Varez is star mining and talking shit to other players. Please wait until varez is finished talking shit.",
    ),
    q(MEME, "Varez just got skulled defending clan turf. Can't respond to randos mid-fight."),
    q(MEME, "Varez is splashing at Rock Crabs and needs 10 more hours before being idle enough to help non-members."),
    q(MEME, "Varez is 1378 KC dry on a Dragon med helm from KBD. Do NOT talk to him right now."),
    q(MEME, "Varez is on attempt 47 of the Fight Caves and Jad keeps slapping him. Your message would seal it."),
    q(MEME, "Varez is doubling money at the GE. Great investment opportunity. Please wait."),
    q(MEME, "Varez is fly fishing Salmon at Barbarian Village for the 6th hour. Dont break his rhythm."),
    q(MEME, "Varez is trimming armor for a stranger at Falador Park. He'll be back once the scam resolves."),
    q(MEME, "Varez is AFK at NMZ with a Guthan setup. Waking him would be a hate crime."),
    q(MEME, "Varez is watching the Falador Massacre VOD for the 400th time. Cultural education, please wait."),
    q(MEME, "Varez is flicking Piety on a Jad attempt. One notification = bones."),
    q(MEME, "Varez is stuck on Evil Bob's island again. He can't hear you from there."),
    q(
        MEME,
        "Varez just got a Draconic visage off the King Black Dragon and is currently screaming. Give him a minute.",
    ),
    q(MEME, "Varez is mining iron at the Al Kharid pit for the 7th day straight. He's no longer verbal."),
    q(MEME, "Varez got hugged by a Vyrewatch on his way to Slayer and needs a second to process."),
    q(MEME, "Varez is 3-iteming at Edge with a DDS and won't leave until someone skulls first."),
    q(MEME, "Varez is being chased by a chicken in Lumbridge. This is his final answer."),
    q(
        MEME,
        "Varez is standing in Falador Park yelling 'selling party hats' at passersby. Not a joke. He's doing it right now.",
    ),
    q(MEME, "Varez is camping a clue step at Zanaris and refuses to move until the scan completes."),
    q(MEME, "Varez is singing Sea Shanty 2 at max volume and refuses to mute."),
    q(MEME, "Varez is 83 Slayer and just got assigned Dust Devils without a slayer helm. He's in a mood."),
    q(MEME, "Varez is alching rune platebodies for 99 Magic and cannot be interrupted mid-click."),
    q(MEME, "Varez is arguing with a Pmod about whether his name is offensive. We'll see how it goes."),
    q(MEME, "Varez is dry 2400 KC at Dagannoth Rex and is composing a formal hate letter to Jagex."),
    q(MEME, "Varez is in World 2 Falador arguing whether Dharok is still meta."),
    q(MEME, "Varez is afking Cosmic Runes through the Abyss for 99 Runecrafting. He'll be back in 2035."),
    q(MEME, "Varez is doing his Penguin Hide & Seek round and has already forgotten which polar bear is the spy."),
    q(MEME, "Varez got Drill Demon'd mid-Jad attempt and is now learning to love again."),
    q(MEME, "Varez is trying to solo the Fight Caves with Initiate harness. Please do not suggest armor upgrades."),
    q(MEME, "Varez is stuck on Monkey Madness because he can't find King Awowogei's hidden door. Again."),
    q(MEME, "Varez is yelling at global chat about how EOC ruined his life. Usual Tuesday."),
    q(MEME, "Varez is at the Stronghold of Security for the 800th time. He wants that ranger boot."),
    q(MEME, "Varez is posting 'GF to lost Blue phat pls bank' in help chat. Classic."),
    q(MEME, "Varez is balancing on a single crate in Varrock Square. It's been 2 hours."),
    q(MEME, "Varez is at Pest Control and got put on Squire duty. He's seething."),
    q(MEME, "Varez is 97% at Seers Agility. Do not sneeze. Do not blink. Do not speak."),
    q(MEME, "Varez is testing a Mith gloves scam on someone in W2 GE. It's going about how you'd expect."),
    q(MEME, "Varez is in clan chat rage-quoting a sandcastle moderator because someone called dragonhide '3A body'."),
    q(MEME, "Varez is granite-mauling someone at 19 wild and just got crashed by a Dharoker. Prayers up."),
    q(MEME, "Varez is telling a stranger at GE that 'abyss is safe, trust me'. Not what you think."),
    q(
        MEME,
        "Varez is challenging random passersby to duels in Varrock Square for a noted anchovy pizza. He's won two.",
    ),
    q(
        MEME,
        "Varez is trying to claim his shooting star loot but the entire W2 trade square has converged on the rocks.",
    ),
    q(MEME, "Varez is baking cakes for a quest and forgot which step he's on. Please hold."),
    q(MEME, "Varez is on dose 3 of 4 against the Dagannoth Kings. Your timing is catastrophic."),
    q(
        MEME,
        "Varez is stuck on the Underground Pass log balance for the 9th time. Send a clan mate to retrieve his bones.",
    ),
    q(MEME, "Varez is safespotting a dragon from behind a pillar. Back after the kill."),
    q(MEME, "Varez got lured to the Lava Maze with 'free items'. He's now poorer, smoother-brained, and quieter."),
    q(
        MEME,
        "Varez is in Falador Park yelling 'I trim, drop armor here' at any noob who walks past. The 76k trick lives on.",
    ),
    q(MEME, "Varez is afking at Mage Bank with prayer up and granite legs. Three hours in, zero opponents."),
    q(MEME, "Varez is hunting green dragons at the Wilderness Volcano and ignoring everyone who isn't a PKer."),
    q(
        MEME,
        "Varez completed the Frog Prince random and is, legally and visually, a princess. He'd rather not talk about it.",
    ),
    q(MEME, "Varez is yelling 'doubling money in CC' from a private chat in Asgarnia. The classics never die."),
    q(
        MEME,
        "Varez opened all six of his Christmas crackers solo and walked away with six pieces of holy bread. Hasnt spoken since.",
    ),
    q(MEME, "Varez is camping the Lumbridge Castle stairs begging for a free bunny mask. Easter 2007 returns."),
    q(MEME, "Varez got teleblocked by a 5-man pure team at GDZ and is currently eating a Karambwan in spirit."),
    q(MEME, "Varez has been in his POH combat ring whacking a clan mate ever since the Construction update went live."),
    q(MEME, "Varez is hosting a drop party at Falador Park. Brace for client lag and one (1) shark."),
];
