import type { BackgroundFields as _BackgroundFields } from "../../fields/field-background.js";
export type BackgroundFields = _BackgroundFields;
import type { ToneExposureFields as _ToneExposureFields } from "../../fields/field-tone-exposure.js";
export type ToneExposureFields = _ToneExposureFields;
import type { BloomFields as _BloomFields } from "../../fields/field-bloom.js";
export type BloomFields = _BloomFields;
import type { OutlineFields as _OutlineFields } from "../../fields/field-outline.js";
export type OutlineFields = _OutlineFields;
import type { VignetteFields as _VignetteFields } from "../../fields/field-vignette.js";
export type VignetteFields = _VignetteFields;
import type { ContrastFields as _ContrastFields } from "../../fields/field-contrast.js";
export type ContrastFields = _ContrastFields;
import type { ChromaticAberrationFields as _ChromaticAberrationFields } from "../../fields/field-chromatic-aberration.js";
export type ChromaticAberrationFields = _ChromaticAberrationFields;
import type { QualityFields as _QualityFields } from "../../fields/field-quality.js";
export type QualityFields = _QualityFields;
