export const LOGIN_STATE_LOGGED_IN = "LOGGED_IN";
export const LOGIN_STATE_LOGGED_OUT = "LOGGED_OUT";
export const LOGIN_STATE_LOGIN_SCREEN = "LOGIN_SCREEN";
export const LOGIN_STATE_LOGIN_SCREEN_AUTHENTICATOR = "LOGIN_SCREEN_AUTHENTICATOR";
export const LOGIN_STATE_LOGGING_IN = "LOGGING_IN";
export const LOGIN_STATE_LOADING = "LOADING";
export const LOGIN_STATE_HOPPING = "HOPPING";
export const LOGIN_STATE_CONNECTION_LOST = "CONNECTION_LOST";
export const LOGIN_STATE_STARTING = "STARTING";
export const LOGIN_STATE_UNKNOWN = "UNKNOWN";
export const LOGIN_STATE_BOOTSTRAPPING = "BOOTSTRAPPING";

export const IN_WORLD_LOGIN_STATES: ReadonlySet<string> = new Set([
    LOGIN_STATE_LOGGED_IN,
    LOGIN_STATE_LOADING,
    LOGIN_STATE_HOPPING,
    LOGIN_STATE_CONNECTION_LOST,
]);
