import { sessionId as _sessionId, nextSeq as _nextSeq } from "./audit-session-id.js";
export const sessionId = _sessionId;
export const nextSeq = _nextSeq;
import { getBuffer as _getBuffer } from "./audit-buffer.js";
export const getBuffer = _getBuffer;
import { getCurrentSlug as _getCurrentSlug, setCurrentSlug as _setCurrentSlug } from "./audit-slug-state.js";
export const getCurrentSlug = _getCurrentSlug;
export const setCurrentSlug = _setCurrentSlug;
import { isStarted as _isStarted, markStarted as _markStarted } from "./audit-started-flag.js";
export const isStarted = _isStarted;
export const markStarted = _markStarted;
