import { createSurfaceSection as _createSurfaceSection } from "../section/split-section-surface.js";
export const createSurfaceSection = _createSurfaceSection;
import { createEmissiveSection as _createEmissiveSection } from "../section/split-section-emissive.js";
export const createEmissiveSection = _createEmissiveSection;
import { coatSheen as _coatSheen } from "../../section-coat-sheen.js";
export const coatSheen = _coatSheen;
import { createWireframeSection as _createWireframeSection } from "../section/split-section-wireframe.js";
export const createWireframeSection = _createWireframeSection;
import { createShadingSection as _createShadingSection } from "../section/split-section-shading.js";
export const createShadingSection = _createShadingSection;
import { createShadowsSection as _createShadowsSection } from "../section/split-section-shadows.js";
export const createShadowsSection = _createShadowsSection;
