import type { PluginConfigField } from "./plugin-config-types.js";

export const PLUGIN_CONFIG_FIELDS_RUNTIME: readonly PluginConfigField[] = [
    {
        key: "streamSkillsSnapshot",
        label: "Skills snapshot",
        description: "Full table on login + change.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamXpGains",
        label: "XP gains",
        description: "Per-skill XP deltas.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamLevelUps",
        label: "Level-ups",
        description: "Per-skill level-up events.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamCombat",
        label: "Combat",
        description: "Hitsplats, target.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamDeath",
        label: "Death",
        description: "Player death events.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamSlayer",
        label: "Slayer",
        description: "Task name, count, master.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamVitals",
        label: "Vitals",
        description: "Run energy, weight, special.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamPrayer",
        label: "Prayer",
        description: "Active prayers.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamBoosts",
        label: "Stat boosts",
        description: "Boost differences.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamStatusEffects",
        label: "Status effects",
        description: "Poison, venom, disease, cold.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamLocation",
        label: "Location",
        description: "Real-time coords visible to clan.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamInventory",
        label: "Inventory",
        description: "Inventory, equipment, seed vault.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamBank",
        label: "Bank",
        description: "Snapshots while open. Reveals wealth.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamRunePouch",
        label: "Rune pouch",
        description: "Slot contents.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamLoot",
        label: "Loot",
        description: "NPC drops + pickups.",
        kind: "boolean",
        defaultValue: true,
    },
    {
        key: "streamPetDrops",
        label: "Pet drops",
        description: "Pet drop events.",
        kind: "boolean",
        defaultValue: true,
    },
];
