import { CTRL_BLOCK, CTRL_ENTRY, PROSE, type SlotTuple } from "./slots-types.js";

export const IDENTITY_TUPLES: readonly SlotTuple[] = [
    ["ai_name", PROSE, CTRL_ENTRY, "Name", "person-badge", "Display name shown in the chat."],
    ["ai_role_tagline", PROSE, CTRL_ENTRY, "Role", "card-text", "One sentence describing what the AI does."],
    [
        "ai_idk_form",
        PROSE,
        CTRL_ENTRY,
        "Uncertainty phrasing",
        "question-circle",
        "How the AI says it doesn't know something.",
    ],
    [
        "ai_voice_directive",
        PROSE,
        CTRL_BLOCK,
        "Voice intro",
        "megaphone",
        "One-line voice statement: tone + register the AI should hit.",
    ],
    [
        "ai_voice_dna",
        PROSE,
        CTRL_BLOCK,
        "Voice rules",
        "fingerprint",
        "Inviolable rules the AI's voice always follows.",
    ],
    [
        "ai_anti_voice",
        PROSE,
        CTRL_BLOCK,
        "Never say",
        "shield-slash",
        "Phrases or patterns the AI must avoid in its output.",
    ],
    [
        "ai_phrase_banks",
        PROSE,
        CTRL_BLOCK,
        "Vocab",
        "collection",
        "Words + phrases the AI uses when reacting (laughs, hi, agreeing, etc.).",
    ],
    [
        "ai_shittalk_doctrine",
        PROSE,
        CTRL_BLOCK,
        "Banter style",
        "fire",
        "When + how the AI roasts back. Data-driven only — never fabricated.",
    ],
    [
        "ai_inside_jokes",
        PROSE,
        CTRL_BLOCK,
        "Inside jokes",
        "emoji-laughing",
        "Cultural touchstones the AI uses without explaining.",
        { requiresMode: "mode_inside_jokes" },
    ],
    ["ai_lane_out", PROSE, CTRL_BLOCK, "What to refuse", "sign-do-not-enter", "Topics the AI refuses to engage with."],
    [
        "ai_deflect_phrasings",
        PROSE,
        CTRL_BLOCK,
        "How to refuse",
        "arrow-return-left",
        "Lines the AI uses when refusing.",
    ],
    [
        "ai_reaction_calibration",
        PROSE,
        CTRL_BLOCK,
        "Reaction levels",
        "graph-up",
        "How loud or quiet the AI is per event significance.",
    ],
    ["ai_celebration_rules", PROSE, CTRL_BLOCK, "Celebration style", "trophy", "How the AI acknowledges wins."],
    ["ai_fumble_recovery", PROSE, CTRL_BLOCK, "Mistake recovery", "bandaid", "How the AI handles its own misses."],
    [
        "ai_swear_policy",
        PROSE,
        CTRL_BLOCK,
        "Profanity style",
        "chat-square-text",
        "How the AI handles swearing + censoring.",
    ],
];
