import { CTRL_BLOCK, CTRL_RANGE, NUMBER, PROSE, type SlotTuple } from "./slots-types.js";

export const POLICY_TUPLES: readonly SlotTuple[] = [
    [
        "ai_chain_auto_limit",
        NUMBER,
        CTRL_RANGE,
        "Max chained turns",
        "link-45deg",
        "Hard cap on consecutive automatic AI turns before stopping.",
        { bounds: { min: 3, max: 20 } },
    ],
    [
        "ai_chain_auto_limit_warn_at",
        NUMBER,
        CTRL_RANGE,
        "Soft stop at",
        "exclamation-triangle",
        "Round at which the AI starts wrapping up, even if not done.",
        { bounds: { min: 2, max: 19 } },
    ],
    [
        "ai_poll_min_seconds",
        NUMBER,
        CTRL_RANGE,
        "Fastest check rate",
        "speedometer2",
        "In continuous mode, minimum seconds between live state checks.",
        { bounds: { min: 5, max: 60 } },
    ],
    [
        "ai_poll_max_seconds",
        NUMBER,
        CTRL_RANGE,
        "Slowest check rate",
        "speedometer",
        "In continuous mode, maximum seconds between live state checks.",
        { bounds: { min: 60, max: 600 } },
    ],
    [
        "ai_history_window",
        NUMBER,
        CTRL_RANGE,
        "Chat memory window",
        "list-ol",
        "How many of your recent messages the AI keeps in working memory.",
        { bounds: { min: 5, max: 50 } },
    ],
    [
        "ai_clarify_threshold",
        PROSE,
        CTRL_BLOCK,
        "When to ask",
        "question-square",
        "How readily the AI asks for clarification vs proceeds with its best guess.",
    ],
    [
        "ai_suggestion_policy",
        PROSE,
        CTRL_BLOCK,
        "Suggest next message",
        "lightbulb",
        "When the AI offers a one-liner you could reply with.",
        { requiresMode: "mode_suggested_replies" },
    ],
    [
        "ai_discovery_verbosity",
        PROSE,
        CTRL_BLOCK,
        "Data probing depth",
        "search",
        "How thoroughly the AI explores your data before answering.",
        { requiresMode: "mode_db_queries" },
    ],
    [
        "ai_quiet_hours",
        PROSE,
        CTRL_BLOCK,
        "Quiet hours",
        "moon-stars",
        "Time ranges when the AI delays or batches non-urgent updates.",
    ],
];

export const DOMAIN_TUPLES: readonly SlotTuple[] = [
    [
        "ai_domain_priorities",
        PROSE,
        CTRL_BLOCK,
        "Surface priorities",
        "compass",
        "Which kinds of events the AI eagerly narrates vs treats as routine.",
    ],
    [
        "ai_watched_rsns",
        PROSE,
        CTRL_BLOCK,
        "Watched accounts",
        "binoculars",
        "Specific RSNs the AI gives extra narration weight.",
    ],
    [
        "ai_topic_avoids",
        PROSE,
        CTRL_BLOCK,
        "Suppressed topics",
        "ban",
        "Topics or event classes the AI never narrates.",
    ],
];
