export const SQL_COLUMNS = {
    ACCOUNT_HASH: "account_hash",
    SITE_ACCOUNT_ID: "site_account_id",
    ITEM_ID: "item_id",
    ITEM_NAME: "item_name",
    QTY_SIGNED: "qty_signed",
    UNIT_PRICE_GP: "unit_price_gp",
} as const;

export type SqlColumnName = (typeof SQL_COLUMNS)[keyof typeof SQL_COLUMNS];

export const SQL_TABLES = {
    CLANSOCKET_CLANS: "clansocket_clans",
    CLANSOCKET_CLAN_MANAGERS: "clansocket_clan_managers",
    CLANSOCKET_CLAN_MANAGER_REQUESTS: "clansocket_clan_manager_requests",
    CLANSOCKET_CLAN_WHITELISTS: "clansocket_clan_whitelists",
    CLANSOCKET_ACCOUNT_BINDINGS: "clansocket_account_bindings",
    CLANSOCKET_ACCOUNT_RSNS: "clansocket_account_rsns",
    CLANSOCKET_ACCOUNT_PROVIDERS: "clansocket_account_providers",
    CLANSOCKET_ACCOUNTS: "clansocket_accounts",
    CLANSOCKET_NOTIFICATIONS: "clansocket_notifications",
    CLANSOCKET_OAUTH_SESSIONS: "clansocket_oauth_sessions",
    CLANSOCKET_PASSKEYS: "clansocket_passkeys",
    CLANSOCKET_DEVICE_LINK_CODES: "clansocket_device_link_codes",
    CLANSOCKET_BACKUP_CODES: "clansocket_backup_codes",
    CLANSOCKET_DATA_ACTION_LOG: "clansocket_data_action_log",
    CLANSOCKET_CONSENT_REQUESTS: "clansocket_consent_requests",
    CLANSOCKET_WEBAUTHN_CHALLENGES: "clansocket_webauthn_challenges",
    CLAN_ROSTERS: "clan_rosters",
    VAREZ_CHAIN_TURNS: "varez_chain_turns",
    VAREZ_PINS: "varez_pins",
    VAREZ_USER_ACTION_LOG: "varez_user_action_log",
    DISCORD_CHANNELS: "discord_channels",
    DISCORD_MEMBERS: "discord_members",
    DISCORD_ROLES: "discord_roles",
    DISCORD_SERVER_EMOJIS: "discord_server_emojis",
    DISCORD_SERVER_STICKERS: "discord_server_stickers",
    DISCORD_GUILD_SETTINGS: "discord_guild_settings",
    DISCORD_WEBHOOKS: "discord_webhooks",
    DISCORD_CHANNEL_ROLE_OVERWRITES: "discord_channel_role_overwrites",
    DISCORD_CHANNEL_MEMBER_OVERWRITES: "discord_channel_member_overwrites",
    DISCORD_SERVERS: "discord_servers",
    DISCORD_BOT_IDENTITIES: "discord_bot_identities",
    DISCORD_BOT_PRESENCE_TEMPLATES: "discord_bot_presence_templates",
    DISCORD_INTERACTIONS_PENDING: "discord_interactions_pending",
    PLUGIN_CURRENT_STATE: "plugin_current_state",
    PLUGIN_PRAYERS: "plugin_prayers",
} as const;

export type SqlTableName = (typeof SQL_TABLES)[keyof typeof SQL_TABLES];
