import js from "@eslint/js";
import tseslint from "typescript-eslint";
import stylistic from "@stylistic/eslint-plugin";
import sonarjs from "eslint-plugin-sonarjs";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const universalRules = require("./universal-rules.cjs");
const listenerWithoutCleanup = require("./eslint-rules/no-listener-without-cleanup.cjs");
const noTimerHeuristic = require("./eslint-rules/no-timer-heuristic.cjs");

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["main/discord/src/**/*.ts"],
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    plugins: {
      "@stylistic": stylistic,
      sonarjs,
      "lvi": {
        rules: {
          ...universalRules.rules,
          "no-listener-without-cleanup": listenerWithoutCleanup,
          "no-timer-heuristic": noTimerHeuristic,
        },
      },
    },
    rules: {
      ...universalRules.severities,
      "lvi/no-listener-without-cleanup": "error",
      "lvi/no-timer-heuristic": "error",

      "sonarjs/argument-type": "error",
      "sonarjs/arguments-order": "error",
      "sonarjs/arguments-usage": "error",
      "sonarjs/array-callback-without-return": "error",
      "sonarjs/array-constructor": "error",
      "sonarjs/bool-param-default": "error",
      "sonarjs/call-argument-line": "error",
      "sonarjs/certificate-transparency": "error",
      "sonarjs/code-eval": "error",
      "sonarjs/cognitive-complexity": ["error", 15],
      "sonarjs/confidential-information-logging": "error",
      "sonarjs/constructor-for-side-effects": "error",
      "sonarjs/content-length": "error",
      "sonarjs/content-security-policy": "error",
      "sonarjs/cookie-no-httponly": "error",
      "sonarjs/cookies": "error",
      "sonarjs/cors": "error",
      "sonarjs/csrf": "error",
      "sonarjs/cyclomatic-complexity": "error",
      "sonarjs/deprecation": "error",
      "sonarjs/different-types-comparison": "error",
      "sonarjs/disabled-auto-escaping": "error",
      "sonarjs/disabled-resource-integrity": "error",
      "sonarjs/disabled-timeout": "error",
      "sonarjs/dns-prefetching": "error",
      "sonarjs/dompurify-unsafe-config": "error",
      "sonarjs/dynamically-constructed-templates": "error",
      "sonarjs/encryption": "error",
      "sonarjs/encryption-secure-mode": "error",
      "sonarjs/expression-complexity": "error",
      "sonarjs/file-permissions": "error",
      "sonarjs/file-uploads": "error",
      "sonarjs/for-loop-increment-sign": "error",
      "sonarjs/frame-ancestors": "error",
      "sonarjs/function-inside-loop": "error",
      "sonarjs/function-return-type": "error",
      "sonarjs/generator-without-yield": "error",
      "sonarjs/hashing": "error",
      "sonarjs/hidden-files": "error",
      "sonarjs/in-operator-type-error": "error",
      "sonarjs/inconsistent-function-call": "error",
      "sonarjs/index-of-compare-to-positive-number": "error",
      "sonarjs/insecure-cookie": "error",
      "sonarjs/insecure-jwt-token": "error",
      "sonarjs/link-with-target-blank": "error",
      "sonarjs/max-switch-cases": "error",
      "sonarjs/max-union-size": "error",
      "sonarjs/misplaced-loop-counter": "error",
      "sonarjs/new-operator-misuse": "error",
      "sonarjs/no-all-duplicated-branches": "error",
      "sonarjs/no-array-delete": "error",
      "sonarjs/no-async-constructor": "error",
      "sonarjs/no-built-in-override": "error",
      "sonarjs/no-case-label-in-switch": "error",
      "sonarjs/no-clear-text-protocols": "error",
      "sonarjs/no-collapsible-if": "error",
      "sonarjs/no-collection-size-mischeck": "error",
      "sonarjs/no-dead-store": "error",
      "sonarjs/no-duplicate-in-composite": "error",
      "sonarjs/no-duplicated-branches": "error",
      "sonarjs/no-element-overwrite": "error",
      "sonarjs/no-empty-collection": "error",
      "sonarjs/no-equals-in-for-termination": "error",
      "sonarjs/no-extra-arguments": "error",
      "sonarjs/no-fallthrough": "error",
      "sonarjs/no-for-in-iterable": "error",
      "sonarjs/no-function-declaration-in-block": "error",
      "sonarjs/no-global-this": "error",
      "sonarjs/no-globals-shadowing": "error",
      "sonarjs/no-gratuitous-expressions": "error",
      "sonarjs/no-hardcoded-ip": "error",
      "sonarjs/no-hardcoded-passwords": "error",
      "sonarjs/no-hardcoded-secrets": "error",
      "sonarjs/no-identical-conditions": "error",
      "sonarjs/no-identical-expressions": "error",
      "sonarjs/no-ignored-exceptions": "error",
      "sonarjs/no-ignored-return": "error",
      "sonarjs/no-implicit-global": "error",
      "sonarjs/no-in-misuse": "error",
      "sonarjs/no-inconsistent-returns": "error",
      "sonarjs/no-incorrect-string-concat": "error",
      "sonarjs/no-internal-api-use": "error",
      "sonarjs/no-intrusive-permissions": "error",
      "sonarjs/no-invariant-returns": "error",
      "sonarjs/no-inverted-boolean-check": "error",
      "sonarjs/no-ip-forward": "error",
      "sonarjs/no-literal-call": "error",
      "sonarjs/no-mime-sniff": "error",
      "sonarjs/no-misleading-array-reverse": "error",
      "sonarjs/no-mixed-content": "error",
      "sonarjs/no-nested-assignment": "error",
      "sonarjs/no-nested-conditional": "error",
      "sonarjs/no-nested-functions": "error",
      "sonarjs/no-nested-incdec": "error",
      "sonarjs/no-nested-switch": "error",
      "sonarjs/no-nested-template-literals": "error",
      "sonarjs/no-os-command-from-path": "error",
      "sonarjs/no-parameter-reassignment": "error",
      "sonarjs/no-primitive-wrappers": "error",
      "sonarjs/no-redundant-assignments": "error",
      "sonarjs/no-redundant-boolean": "error",
      "sonarjs/no-redundant-jump": "error",
      "sonarjs/no-redundant-optional": "error",
      "sonarjs/no-redundant-parentheses": "error",
      "sonarjs/no-referrer-policy": "error",
      "sonarjs/no-same-argument-assert": "error",
      "sonarjs/no-same-line-conditional": "error",
      "sonarjs/no-selector-parameter": "error",
      "sonarjs/no-session-cookies-on-static-assets": "error",
      "sonarjs/no-small-switch": "error",
      "sonarjs/no-try-promise": "error",
      "sonarjs/no-undefined-argument": "error",
      "sonarjs/no-undefined-assignment": "error",
      "sonarjs/no-unenclosed-multiline-block": "error",
      "sonarjs/no-unsafe-unzip": "error",
      "sonarjs/no-unthrown-error": "error",
      "sonarjs/no-unused-collection": "error",
      "sonarjs/no-use-of-empty-return-value": "error",
      "sonarjs/no-useless-catch": "error",
      "sonarjs/no-useless-increment": "error",
      "sonarjs/no-useless-intersection": "error",
      "sonarjs/no-variable-usage-before-declaration": "error",
      "sonarjs/no-weak-cipher": "error",
      "sonarjs/no-weak-keys": "error",
      // Conflicts with factory barrel re-export architecture (single import
      // surface via `export * from "./X"` chain). Project doctrine wins.
      "sonarjs/no-wildcard-import": "off",
      "sonarjs/non-existent-operator": "error",
      "sonarjs/non-number-in-arithmetic-expression": "error",
      "sonarjs/null-dereference": "error",
      "sonarjs/operation-returning-nan": "error",
      "sonarjs/os-command": "error",
      "sonarjs/post-message": "error",
      "sonarjs/prefer-default-last": "error",
      // Superseded by lvi/prefer-immediate-return (same detection +
      // function-level allowlist for cross-rule reconciliation with
      // lvi/no-untracked-observer).
      "sonarjs/prefer-immediate-return": "off",
      "sonarjs/prefer-object-literal": "error",
      "sonarjs/prefer-promise-shorthand": "error",
      "sonarjs/prefer-single-boolean-return": "error",
      "sonarjs/prefer-type-guard": "error",
      "sonarjs/prefer-while": "error",
      "sonarjs/process-argv": "error",
      "sonarjs/production-debug": "error",
      "sonarjs/pseudo-random": "error",
      "sonarjs/public-static-readonly": "error",
      "sonarjs/publicly-writable-directories": "error",
      "sonarjs/reduce-initial-value": "error",
      "sonarjs/redundant-type-aliases": "error",
      "sonarjs/session-regeneration": "error",
      "sonarjs/shorthand-property-grouping": "error",
      "sonarjs/sockets": "error",
      "sonarjs/sql-queries": "error",
      "sonarjs/standard-input": "error",
      "sonarjs/strict-transport-security": "error",
      "sonarjs/strings-comparison": "error",
      "sonarjs/too-many-break-or-continue-in-loop": "error",
      "sonarjs/unverified-certificate": "error",
      "sonarjs/unverified-hostname": "error",
      "sonarjs/updated-const-var": "error",
      "sonarjs/updated-loop-counter": "error",
      "sonarjs/use-type-alias": "error",
      "sonarjs/useless-string-operation": "error",
      "sonarjs/values-not-convertible-to-numbers": "error",
      // Conflicts with lvi/no-floating-promise which uses `void X` as the
      // explicit fire-and-forget marker (TS-ecosystem standard idiom). lvi
      // wins as project-authored doctrine.
      "sonarjs/void-use": "off",
      "sonarjs/weak-ssl": "error",
      "sonarjs/x-powered-by": "error",
      "sonarjs/xml-parser-xxe": "error",
      "sonarjs/xpath": "error",

      "no-empty": "off",
      "no-trailing-spaces": "off",
      "no-multiple-empty-lines": "off",
      "eol-last": "off",
      "@stylistic/no-trailing-spaces": "error",
      "@stylistic/no-multiple-empty-lines": ["error", { max: 1 }],
      "@stylistic/eol-last": "error",

      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "*.config.*",
    ],
  },
);
