const BYTES_PER_KILOBYTE = 1024;
const BYTES_PER_MEGABYTE = BYTES_PER_KILOBYTE * BYTES_PER_KILOBYTE;

export const FIVE_MB_BYTES = 5 * BYTES_PER_MEGABYTE;
export const TEN_MB_BYTES = 10 * BYTES_PER_MEGABYTE;
export const FIFTY_MB_BYTES = 50 * BYTES_PER_MEGABYTE;
