import type * as P from "./audit-payload-shapes.js";
import type * as D from "./discord-payload-shapes.js";

export type PayloadMap = {
    "server:roster.changed": P.RosterChangedPayload;
    "server:claim.completed": P.ClaimCompletedPayload;
    "server:claim.transferred": P.ClaimTransferredPayload;
    "server:claim.rejected": P.ClaimRejectedPayload;
    "server:claim.consent_requested": P.ConsentRequestedPayload;
    "server:claim.consent_confirmed": P.ConsentResolvedPayload;
    "server:claim.consent_rejected": P.ConsentResolvedPayload;
    "server:manager.granted": P.ManagerGrantedPayload;
    "server:manager.revoked": P.ManagerRevokedPayload;
    "server:manager.request.created": P.RequestCreated;
    "server:manager.request.approved": P.RequestResolved;
    "server:manager.request.denied": P.RequestResolved;
    "server:branding.updated": P.BrandingUpdatedPayload;
    "server:branding.customized": P.BrandingCustomizedPayload;
    "server:seo.updated": P.SeoUpdatedPayload;
    "server:whitelist.added": P.WhitelistAddedPayload;
    "server:whitelist.removed": P.WhitelistRemovedPayload;
    "server:auth.rejected": P.AuthRejectedPayload;
    "server:read.managers": P.ReadAuditPayload;
    "server:read.manager_requests": P.ReadAuditPayload;
    "server:read.audit_log": P.ReadAuditPayload;
    "server:read.roster_diffs": P.ReadAuditPayload;
    "server:read.whitelist": P.ReadAuditPayload;
    "client:click": P.ClientClickPayload;
    "client:submit": P.ClientSubmitPayload;
    "client:route": P.ClientRoutePayload;
    "vault:discord-bot.read": P.VaultBotRead;
    "vault:discord-bot.write": P.VaultBotWrite;
    "vault:discord-bot.delete": P.VaultBotDelete;
    "vault:discord-bot.verify": P.VaultBotVerify;
    "vault:wom.read": P.VaultWomRead;
    "vault:wom.write": P.VaultWomWrite;
    "vault:wom.delete": P.VaultWomDelete;
    "vault:wom.verify": P.VaultWomVerify;
    "wom:link.linker_reassigned": P.WomLinkerReassigned;
    "wom:rsn.changed": P.WomRsnChanged;
    "wom:backfill.completed": P.WomBackfillDone;
    "wom:backfill.failed": P.WomBackfillFailed;
    "discord:channels.create": D.ChannelsCreate;
    "discord:channels.update": D.ChannelsUpdate;
    "discord:channels.delete": D.ChannelsDelete;
    "discord:channels.move": D.ChannelsMove;
    "discord:channels.set-permissions": D.ChannelsSetPerms;
    "discord:channels.delete-permissions": D.ChannelsDeletePerms;
    "discord:roles.create": D.RolesCreate;
    "discord:roles.update": D.RolesUpdate;
    "discord:roles.delete": D.RolesDelete;
    "discord:roles.set-position": D.RolesPosition;
    "discord:roles.set-permissions": D.RolesPerms;
    "discord:bot.linker_reassigned": D.BotLinkerReassigned;
    "discord:members.set-nickname": D.MembersNickname;
    "discord:members.add-role": D.MembersAddRole;
    "discord:members.remove-role": D.MembersRemoveRole;
    "discord:members.timeout": D.MembersTimeout;
    "discord:members.kick": D.MembersKick;
    "discord:members.ban": D.MembersBan;
    "discord:members.unban": D.MembersUnban;
    "discord:webhooks.create": D.WebhooksCreate;
    "discord:webhooks.update": D.WebhooksUpdate;
    "discord:webhooks.delete": D.WebhooksDelete;
    "discord:webhooks.regenerate-token": D.WebhooksRegenToken;
    "discord:webhook-tokens.revoke": D.WebhookTokenRevoked;
    "discord:server-emojis.create": D.EmojisCreate;
    "discord:server-emojis.rename": D.EmojisRename;
    "discord:server-emojis.delete": D.EmojisDelete;
    "discord:server-stickers.create": D.StickersCreate;
    "discord:server-stickers.rename": D.StickersRename;
    "discord:server-stickers.delete": D.StickersDelete;
    "discord:guild-settings.set-name": D.GuildSetName;
    "discord:guild-settings.set-icon": D.GuildSetIcon;
    "discord:guild-settings.set-banner": D.GuildSetBanner;
    "discord:guild-settings.set-description": D.GuildSetDescription;
    "discord:guild-settings.set-system-channel": D.GuildSysChannel;
    "discord:guild-settings.set-afk": D.GuildSetAfk;
    "discord:guild-settings.set-welcome-screen": D.GuildWelcomeScreen;
    "discord:guild-settings.set-verification-level": D.GuildVerifyLevel;
    "discord:auto-hooks.create": D.AutoHookCreated;
    "discord:auto-hooks.update": D.AutoHookUpdated;
    "discord:auto-hooks.delete": D.AutoHookDeleted;
    "discord:auto-hooks.toggle": D.AutoHookToggled;
};

export type AnyAuditAction = keyof PayloadMap;
export type PayloadFor<A extends AnyAuditAction> = PayloadMap[A];
