export const META_TAGS = [
    "nav",
    "action",
    "destructive",
    "input",
    "choice",
    "submit",
    "disclosure",
    "data",
    "metric",
    "chart",
    "feed",
    "leaderboard",
    "roster",
    "award",
    "rivalry",
    "clan",
    "rsn",
    "account",
    "device",
    "audit",
    "notification",
    "modal",
    "panel",
    "toast",
    "tooltip",
    "copy",
    "discord",
    "emoji",
    "external",
    "plugin-config",
] as const;

export type MetaTag = (typeof META_TAGS)[number];
