import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { mkdirSync, writeFileSync } from "fs";
import "../../main/dashboard/src/app/routes.js";
import { routeDefs } from "../../main/dashboard/src/managers/router/registry.js";

const here = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(here, "..", "..", "main/server/src/ai/prompts/auto-gen");
const OUTPUT = join(OUTPUT_DIR, "web-routing.json");
const README = join(OUTPUT_DIR, "README.md");

const README_BODY = `# auto-gen

generated files. do not hand-edit.

\`web-routing.json\` — the app's route table (pattern + description per route), derived from the dashboard's self-registered routes (the \`defineRoute\` calls collected by \`routeDefs()\`). regenerated by \`scripts/build-scripts/build-web-routes-script.ts\` on every build (\`npm run sync:web-routes\`, wired into \`npm run chain:build\` via \`chain:sync:all\`). add or remove a route in the dashboard and it reflects here automatically. the \`dashboard-web-routing\` ai provider reads this file at startup.
`;

const routes = routeDefs().map((d) => ({
    pattern: d.example ?? d.path,
    description: d.description,
}));

mkdirSync(OUTPUT_DIR, { recursive: true });
writeFileSync(OUTPUT, JSON.stringify({ routes }, null, 4) + "\n", "utf-8");
writeFileSync(README, README_BODY, "utf-8");
console.log(`web-routing synced: ${routes.length} route(s) -> ${OUTPUT}`);
