import { fileURLToPath, pathToFileURL } from "url";
import { dirname, join } from "path";
import { mkdirSync, readdirSync, writeFileSync } from "fs";
import type { RouteDef } from "../../main/dashboard/src/managers/router/types.js";

const here = dirname(fileURLToPath(import.meta.url));
const DASHBOARD_DOM = join(here, "..", "..", "main", "dashboard", "src", "dom");
const OUTPUT_DIR = join(here, "..", "..", "main/server/src/ai/prompts/auto-gen");
const OUTPUT = join(OUTPUT_DIR, "web-routing.json");
const README = join(OUTPUT_DIR, "README.md");

const ROUTE_FILE_SUFFIX = "-route.ts";
const ROUTES_DIR_SEGMENT_POSIX = "/routes/";
const ROUTES_DIR_SEGMENT_WIN = "\\routes\\";

const README_BODY = `# auto-gen

generated files. do not hand-edit.

\`web-routing.json\` — the app's route table (pattern + description per route), derived from the dashboard's self-registered routes (the \`defineRoute\` calls collected by \`routeDefs()\`). regenerated by \`scripts/build-scripts/build-web-routes-script.ts\` on every build (\`npm run sync:web-routes\`, wired into \`npm run chain:build\` via \`chain:sync:all\`). add or remove a route in the dashboard and it reflects here automatically. the \`dashboard-web-routing\` ai provider reads this file at startup.
`;

function isRouteFile(fullPath: string, baseName: string): boolean {
    if (!baseName.endsWith(ROUTE_FILE_SUFFIX)) return false;
    return fullPath.includes(ROUTES_DIR_SEGMENT_POSIX) || fullPath.includes(ROUTES_DIR_SEGMENT_WIN);
}

function findRouteFiles(root: string): string[] {
    const found: string[] = [];
    const entries = readdirSync(root, { recursive: true, withFileTypes: true });
    for (const entry of entries) {
        if (!entry.isFile()) continue;
        const parent = entry.parentPath;
        const fullPath = join(parent, entry.name);
        if (isRouteFile(fullPath, entry.name)) found.push(fullPath);
    }
    return found.sort();
}

async function main(): Promise<void> {
    const routeFiles = findRouteFiles(DASHBOARD_DOM);
    for (const file of routeFiles) {
        await import(pathToFileURL(file).href);
    }
    const registryPath = join(here, "..", "..", "main", "dashboard", "src", "managers", "router", "registry.ts");
    const registry = (await import(pathToFileURL(registryPath).href)) as {
        routeDefs: () => readonly RouteDef[];
    };
    const routes = registry.routeDefs().map((d) => ({
        pattern: d.example ?? d.path,
        description: d.description,
    }));
    mkdirSync(OUTPUT_DIR, { recursive: true });
    writeFileSync(OUTPUT, JSON.stringify({ routes }, null, 4) + "\n", "utf-8");
    writeFileSync(README, README_BODY, "utf-8");
    console.log(`web-routing synced: ${routes.length} route(s) -> ${OUTPUT}`);
}

void main();
