import {
    DEFAULT_BEZIER_TOLERANCE,
    DEFAULT_CORNER_ANGLE_DEGREES,
    DEFAULT_EXTRUSION_DEPTH,
    DEFAULT_SMOOTHING_PASSES,
    DEFAULT_TAUBIN_LAMBDA,
    DEFAULT_TAUBIN_MU,
    DEFAULT_TAUBIN_ROUNDS,
    MAX_BEZIER_TOLERANCE,
    MAX_CORNER_ANGLE_DEGREES,
    MAX_EXTRUSION_DEPTH,
    MAX_SMOOTHING_PASSES,
    MAX_TAUBIN_LAMBDA,
    MAX_TAUBIN_MU,
    MAX_TAUBIN_ROUNDS,
    MIN_BEZIER_TOLERANCE,
    MIN_CORNER_ANGLE_DEGREES,
    MIN_EXTRUSION_DEPTH,
    MIN_SMOOTHING_PASSES,
    MIN_TAUBIN_LAMBDA,
    MIN_TAUBIN_MU,
    MIN_TAUBIN_ROUNDS,
} from "./constants/defaults.js";
import type { NumericBounds } from "./resolve-options-types.js";

export const RESOLVE_BOUNDS: Record<string, NumericBounds> = {
    tolerance: { fallback: DEFAULT_BEZIER_TOLERANCE, min: MIN_BEZIER_TOLERANCE, max: MAX_BEZIER_TOLERANCE },
    depth: { fallback: DEFAULT_EXTRUSION_DEPTH, min: MIN_EXTRUSION_DEPTH, max: MAX_EXTRUSION_DEPTH },
    smooth: { fallback: DEFAULT_SMOOTHING_PASSES, min: MIN_SMOOTHING_PASSES, max: MAX_SMOOTHING_PASSES },
    taubin: { fallback: DEFAULT_TAUBIN_ROUNDS, min: MIN_TAUBIN_ROUNDS, max: MAX_TAUBIN_ROUNDS },
    lambda: { fallback: DEFAULT_TAUBIN_LAMBDA, min: MIN_TAUBIN_LAMBDA, max: MAX_TAUBIN_LAMBDA },
    mu: { fallback: DEFAULT_TAUBIN_MU, min: MIN_TAUBIN_MU, max: MAX_TAUBIN_MU },
    corner: { fallback: DEFAULT_CORNER_ANGLE_DEGREES, min: MIN_CORNER_ANGLE_DEGREES, max: MAX_CORNER_ANGLE_DEGREES },
};
